#!/usr/bin/env bash
sudo apt install software-properties-common --yes
sudo apt-add-repository --yes --update ppa:ansible/ansible
sudo apt install ansible --yes

# Plugin to stow in ansible
curl -o stow https://raw.githubusercontent.com/caian-org/ansible-stow/v0.1.4/stow
sudo mkdir -p /usr/share/ansible/plugins/modules/
sudo mv stow /usr/share/ansible/plugins/modules/

ansible-playbook --ask-vault-pass --ask-become-pass local.yml
