- name: Install packages
  become: true
  apt:
    name:
      [
        "build-essential",
        "tmux",
        "zip",
        "unzip",
        "curl",
        "git",
        "fzf",
        "bat",
        "wget",
        "fd-find",
        "tldr",
        "ripgrep",
        "direnv",
        "moreutils",
        "less",
        "stow",
        "apt-transport-https",
      ]
  tags:
    - install
    - neovim
    - core
- name: Add Yarn apt key
  become: true
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
  tags:
    - install
    - neovim
    - core
    - dotfiles
- name: Add Yarn repository
  become: true
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    filename: yarn
  tags:
    - install
    - neovim
    - core
    - dotfiles
- name: Install Yarn
  become: true
  apt:
    name: yarn
  tags:
    - install
    - neovim
    - core
    - dotfiles
- name: Get starship install script
  get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: "0755"
  tags:
    - install
    - neovim
    - core
    - dotfiles
- name: Install starship
  become: true
  shell:
    cmd: /tmp/starship_install.sh --yes
    executable: /bin/sh
  tags:
    - install
    - neovim
    - core
    - dotfiles
- name: Getting last exa_version
  shell: curl -s "https://api.github.com/repos/ogham/exa/releases/latest" | grep -Po '"tag_name"{{ ":" }} "v\K[0-9.]+'
  register: EXA_VERSION
  tags:
    - test
    - install
    - neovim
    - core
    - dotfiles
- name: Downloading exa
  shell: curl -Lo exa.zip "https://github.com/ogham/exa/releases/latest/download/exa-linux-x86_64-v{{EXA_VERSION.stdout}}.zip"
  tags:
    - test
    - install
    - neovim
    - core
    - dotfiles
- name: Install exa
  become: true
  shell: unzip -qo exa.zip bin/exa -d /usr/local
  tags:
    - test
    - install
    - neovim
    - core
    - dotfiles
- name: Remove exa.zip
  shell: rm -rf exa.zip
  tags:
    - test
    - install
    - neovim
    - core
    - dotfiles
- name: Getting last lazygit_version
  shell: curl -s "https://api.github.com/repos/jesseduffield/lazygit/releases/latest"| grep -Po '"tag_name"{{ ":" }} "v\K[0-35.]+'
  register: LAZYGIT_VERSION
  tags:
    - test
    - install
    - neovim
    - core
    - dotfiles
- name: Downloading lazygit
  shell: curl -Lo lazygit.tar.gz "https://github.com/jesseduffield/lazygit/releases/latest/download/lazygit_{{LAZYGIT_VERSION.stdout}}_Linux_x86_64.tar.gz""
  tags:
    - test
    - install
    - neovim
    - core
    - dotfiles
- name: Install lazygit
  become: true
  shell: tar --overwrite xf lazygit.tar.gz -C /usr/local/bin lazygit
  tags:
    - test
    - install
    - neovim
    - core
    - dotfiles
- name: Remove lazygit.tar.gz
  shell: rm -rf lazygit.tar.gz
  tags:
    - test
    - install
    - neovim
    - core
    - dotfiles
