- name: Clone .dotfiles
  shell: cd $HOME/ansible && ./clone-dotfiles.sh
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles/ && ./stow-folders.sh
  tags:
    - install
    - dotfiles
    - stow
