- name: Remove Neovim
  shell: rm -rf ~/neovim
  tags:
    - install
    - neovim
- name: Clone Neovim
  ansible.builtin.git:
    repo: "https://github.com/neovim/neovim.git"
    dest: "{{ lookup('env', 'HOME') }}/neovim"
  tags:
    - install
    - neovim
- name: Install build prerequisites
  become: true
  apt:
    name:
      [
        "libpthread-stubs0-dev",
        "lua5.1",
        "ninja-build",
        "gettext",
        "libtool",
        "libtool-bin",
        "autoconf",
        "automake",
        "cmake",
        "g++",
        "pkg-config",
        "doxygen",
        "clang",
        "clang-11",
        "clang-12",
        "clangd",
        "clangd-10",
        "clangd-11",
        "clangd-12",
      ]
  tags:
    - install
    - neovim
- name: Install Neovim
  become: true
  shell: "make CMAKE_INSTALL_PREFIX={{ lookup('env', 'HOME') }}/neovim CMAKE_BUILD_TYPE=Release install"
  tags:
    - install
    - neovim
