- name: Install ZSH
  become: true
  apt:
    name: zsh
    state: latest
  tags:
    - "install"
    - "dotfiles"
    - "zsh"
# - name: Register current user (workaround to change default shell)
#   shell: whoami
#   register: current_user
# - name: Change shell to zsh
#   become: true
#   shell: "chsh -s $(which zsh) {{ current_user.stdout}}"
- name: Change shell to zsh
  become: true
  user:
    name: "{{ current_user }}"
    shell: /bin/zsh
  tags:
    - "install"
    - "dotfiles"
    - "zsh"
